### ISSUE TITLE
The page is broken

### ISSUE THREAD

**Issue by fabioaraujopt** [crdsdev/doc#169] opened 2023-01-11 09:47 UTC
This lib became unavailable:

`https://unpkg.com/react-table@7.8.0/dist/react-table.production.min.js`

This is making the JS break with:

`Uncaught ReferenceError: ReactTable is not defined`

**Comment by hasheddan** [comment] 2023-02-09 15:00
@fabioaraujopt I am unable to reproduce this behavior -- are you still seeing it?

**Comment by hasheddan** [comment] 2023-04-03 11:29
@fabioaraujopt I am going to close this for now, but please reopen if you are still seeing this behavior!

**Closed as completed by hasheddan** 2023-04-03 11:29 UTC
